# Resolve o react_native_pods.rb com node para permitir hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require 'fileutils'

platform :ios, '16.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
end

target 'ecooperativa' do
  config = use_native_modules!

  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true

  pod 'RNSVG', :path => '../node_modules/react-native-svg', :modular_headers => true
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient', :modular_headers => true
  pod 'react-native-video', :path => '../node_modules/react-native-video', :modular_headers => true
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf', :modular_headers => true 
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker', :modular_headers => true
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage', :modular_headers => true
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker', :modular_headers => true
  pod 'react-native-biometrics', :path => '../node_modules/react-native-biometrics', :modular_headers => true
  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util', :modular_headers => true
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info', :modular_headers => true
  pod 'CodePush', :path => '../node_modules/@revopush/react-native-code-push', :modular_headers => true
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  if ENV['RCT_NEW_ARCH_ENABLED'] == '1'
    ENV['DISABLE_POD_INSTALL_STATS'] = 'true'
    
    pod 'React-Core', :path => config[:reactNativePath]
    pod 'React-RCTFabric', :path => config[:reactNativePath]
    pod 'React-RCTText', :path => config[:reactNativePath]
    pod 'React-RCTImage', :path => config[:reactNativePath]
    pod 'React-RCTAnimation', :path => config[:reactNativePath]
    pod 'React-RCTNetwork', :path => config[:reactNativePath]
    pod 'React-RCTSettings', :path => config[:reactNativePath]
    pod 'React-RCTVibration', :path => config[:reactNativePath]
    pod 'React-Codegen', :path => config[:reactNativePath]
    pod 'RCT-Folly', :path => config[:reactNativePath]
    pod 'RCTRequired', :path => config[:reactNativePath]
    pod 'RCTTypeSafety', :path => config[:reactNativePath]
    pod 'ReactCommon', :path => config[:reactNativePath]
    pod 'React-hermes', :path => config[:reactNativePath]
    pod 'hermes-engine'
    pod 'React-jsi', :path => config[:reactNativePath]
    pod 'React-jsc', :path => config[:reactNativePath]
    pod 'React-Fabric', :path => config[:reactNativePath]
    pod 'React-graphics', :path => config[:reactNativePath]
    pod 'React-debug', :path => config[:reactNativePath]
    pod 'React-Image', :path => config[:reactNativePath]
    pod 'Folly', :path => config[:reactNativePath]
  end

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if ['glog', 'fmt', 'React-hermes', 'hermes-engine'].include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
    end
  end
end
